// Auto-generated by training/quantize_export.py
`ifndef NPU_PARAMS_VH
`define NPU_PARAMS_VH

`define INPUT_SIZE 784
`define HIDDEN_SIZE 64
`define OUTPUT_SIZE 26
`define SHIFT_L1 10

// Quantization debug info
// INPUT_SCALE = 0.00392156862745
// W1_SCALE    = 0.0142092535815
// W2_SCALE    = 0.00990990109331

`endif
