import argparse
from pathlib import Path

import numpy as np
import torch


def quantize_weight_symmetric(weight):
    """
    float weight를 signed int8 범위(-127~127)로 대칭 양자화한다.

    반환값:
    - q_weight: int8 weight
    - scale: float weight를 q_weight로 나눌 때 사용한 scale

    식:
        q = round(weight / scale)
        scale = max(abs(weight)) / 127
    """
    max_abs = float(np.max(np.abs(weight)))

    # 모든 값이 0인 경우 0으로 나누는 것을 막기 위한 방어 코드이다.
    if max_abs == 0.0:
        scale = 1.0
    else:
        scale = max_abs / 127.0

    q_weight = np.round(weight / scale)
    q_weight = np.clip(q_weight, -127, 127).astype(np.int8)

    return q_weight, scale


def quantize_bias_for_accum(bias, input_scale, weight_scale):
    """
    float bias를 accumulator에서 더할 int32 bias로 변환한다.

    Linear layer의 float 계산은 대략 다음과 같다.
        y = sum(x_float * w_float) + bias_float

    RTL에서는 x와 w를 정수로 쓰므로 accumulator 단위가
        input_scale * weight_scale
    이 된다. 따라서 bias도 같은 단위의 int32로 바꿔야 한다.
    """
    accum_scale = input_scale * weight_scale
    q_bias = np.round(bias / accum_scale)
    return q_bias.astype(np.int32)


def write_int8_hex(path, array):
    """
    int8 배열을 2자리 hex 텍스트로 저장한다.

    음수는 2의 보수로 저장된다.
    예: -1 -> ff, 10 -> 0a
    """
    flat = array.reshape(-1)
    with path.open('w') as f:
        for value in flat:
            f.write(f'{int(value) & 0xff:02x}\n')


def write_int32_hex(path, array):
    """
    int32 배열을 8자리 hex 텍스트로 저장한다.

    음수는 2의 보수로 저장된다.
    예: -1 -> ffffffff, 25 -> 00000019
    """
    flat = array.reshape(-1)
    with path.open('w') as f:
        for value in flat:
            f.write(f'{int(value) & 0xffffffff:08x}\n')


def write_params(path, shift_l1, scale_x, scale_w1, scale_w2):
    """
    RTL에서 공통으로 쓸 수 있는 layer 크기와 shift 값을 Verilog header로 저장한다.

    scale 값은 RTL에서 직접 쓰지는 않지만, 나중에 디버깅할 때
    Python 양자화 설정을 추적하기 위해 주석으로 남긴다.
    """
    bt = chr(96)
    text = f"""// Auto-generated by training/quantize_export.py
{bt}ifndef NPU_PARAMS_VH
{bt}define NPU_PARAMS_VH

{bt}define INPUT_SIZE 784
{bt}define HIDDEN_SIZE 64
{bt}define OUTPUT_SIZE 26
{bt}define SHIFT_L1 {shift_l1}

// Quantization debug info
// INPUT_SCALE = {scale_x:.12g}
// W1_SCALE    = {scale_w1:.12g}
// W2_SCALE    = {scale_w2:.12g}

{bt}endif
"""
    path.write_text(text)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--model', default='./model.pth')
    parser.add_argument('--out-dir', default='./exported')
    parser.add_argument('--shift-l1', type=int, default=8)
    args = parser.parse_args()

    model_path = Path(args.model)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # train_emnist.py에서 저장한 checkpoint를 읽는다.
    checkpoint = torch.load(model_path, map_location='cpu')
    state = checkpoint['model_state'] if 'model_state' in checkpoint else checkpoint

    # PyTorch Linear weight shape:
    # fc1.weight: [64, 784]
    # fc2.weight: [26, 64]
    w1 = state['fc1.weight'].numpy()
    b1 = state['fc1.bias'].numpy()
    w2 = state['fc2.weight'].numpy()
    b2 = state['fc2.bias'].numpy()

    # 학습 때 입력은 0.0~1.0 float였다.
    # RTL에서는 0~255 uint8 pixel을 사용할 예정이므로 scale은 1/255로 둔다.
    input_scale = 1.0 / 255.0

    q_w1, scale_w1 = quantize_weight_symmetric(w1)
    q_w2, scale_w2 = quantize_weight_symmetric(w2)

    q_b1 = quantize_bias_for_accum(b1, input_scale, scale_w1)

    # L2 입력 hidden은 L1 accumulator를 SHIFT_L1만큼 right shift한 uint8 값이다.
    # 여기서는 hidden 1 count가 float 기준 어느 정도인지를 근사해서 bias scale을 맞춘다.
    hidden_scale = input_scale * scale_w1 * (2 ** args.shift_l1)
    q_b2 = quantize_bias_for_accum(b2, hidden_scale, scale_w2)

    write_int8_hex(out_dir / 'weights_l1.txt', q_w1)
    write_int8_hex(out_dir / 'weights_l2.txt', q_w2)
    write_int32_hex(out_dir / 'biases_l1.txt', q_b1)
    write_int32_hex(out_dir / 'biases_l2.txt', q_b2)
    write_params(out_dir / 'npu_params.vh', args.shift_l1, input_scale, scale_w1, scale_w2)

    print(f'model       : {model_path}')
    print(f'out dir     : {out_dir}')
    print(f'w1 shape    : {q_w1.shape}, scale={scale_w1:.8g}')
    print(f'w2 shape    : {q_w2.shape}, scale={scale_w2:.8g}')
    print(f'b1 shape    : {q_b1.shape}')
    print(f'b2 shape    : {q_b2.shape}')
    print(f'shift_l1    : {args.shift_l1}')
    print('export done')


if __name__ == '__main__':
    main()
